# Generated by Django 4.2.3 on 2023-07-19 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Формат: обязательный, максимальная длина символов - 255', max_length=255, verbose_name='Имя товара')),
                ('slug', models.SlugField(help_text='Формат: обязательный, максимальная длина символов - 255', max_length=255, verbose_name='Путь до товара')),
                ('description', models.TextField(help_text='Формат: необязательный', verbose_name='Описание товара')),
                ('deleted', models.BooleanField(help_text='Выбрать, если товар должна быть удалена', verbose_name='Удаление')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Формат: обязательный, максимальная длина символов - 255', max_length=255, verbose_name='Имя категории товара')),
                ('slug', models.SlugField(help_text='Формат: обязательный, максимальная длина символов - 255', max_length=255, verbose_name='Путь до категории товара')),
                ('deleted', models.BooleanField(help_text='Выбрать, если категория должна быть удалена', verbose_name='Удаление')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(help_text='Формат: обязательный', upload_to='', verbose_name='Фото товара')),
                ('deleted', models.BooleanField(help_text='Выбрать, если фото товара должна быть удалена', verbose_name='Удаление')),
                ('product', models.ForeignKey(help_text='Формат: обязательный', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productmedias', to='dbcore.product', verbose_name='Товар, к которому относится фото')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фото товаров',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Формат: обязательный, максимальная длина символов - 255', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='dbcore.productcategory', verbose_name='Категория товара'),
        ),
    ]
