# Generated by Django 4.2.3 on 2023-09-18 20:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='EmailEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '5. Имейлы',
                'verbose_name_plural': '5. Имейлы',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=20, verbose_name='Почта')),
                ('text', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': '4. Клиентская заявка',
                'verbose_name_plural': '4. Клиентские заявки',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ru', 'ru'), ('eng', 'eng'), ('kz', 'kz')], max_length=3, unique=True, verbose_name='Языковая раскладка')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название слайда')),
                ('lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='dbcore.language', verbose_name='Язык')),
            ],
            options={
                'verbose_name': '2. Слайд с предложениями',
                'verbose_name_plural': '2. Слайды с предложениями',
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='Имя компании')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Главный текст')),
                ('lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mainpages', to='dbcore.language', verbose_name='Язык')),
            ],
            options={
                'verbose_name': '1. Главная страница',
                'verbose_name_plural': '1. Главная страница',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infos', to='dbcore.language', verbose_name='Язык')),
            ],
            options={
                'verbose_name': '3. Информация',
                'verbose_name_plural': '3. Информация',
            },
        ),
        migrations.CreateModel(
            name='ChildOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст заголовка')),
                ('img', models.ImageField(upload_to='', verbose_name='Картинка позади текста')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childoffers', to='dbcore.offer', verbose_name='Слайд')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.CreateModel(
            name='ChildCategoryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('category_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childcategoryinfos', to='dbcore.categoryinfo', verbose_name='Слайд')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегория',
            },
        ),
        migrations.AddField(
            model_name='categoryinfo',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoryinfos', to='dbcore.info', verbose_name='Главный текст'),
        ),
    ]
