# Generated by Django 4.2.3 on 2023-07-21 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата получения')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Время получения')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='FeedbackEmailEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата отправки')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('send', models.BooleanField(default=False, help_text='Галочка стоит, если сообщение отправлено на Вашу почту', verbose_name='Отправлено')),
                ('feedback', models.ForeignKey(help_text='Заявка, к которой относится уведомление на Вашу почту', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='dbcore.feedback', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Уведомление на почту о заявке',
                'verbose_name_plural': 'Уведомления на почту о заявке',
            },
        ),
    ]
