# Generated by Django 4.2.3 on 2023-08-04 15:56

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0002_feedback_feedbackemailentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('img', models.ImageField(upload_to='', verbose_name='Фото')),
                ('text', models.ImageField(upload_to='', verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.ImageField(upload_to='', verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('RU', 'RU'), ('ENG', 'ENG'), ('KZ', 'KZ')], max_length=3, unique=True, verbose_name='Языковая раскладка')),
            ],
        ),
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maininfos', to='dbcore.language', verbose_name='Язык')),
            ],
        ),
        migrations.CreateModel(
            name='MainOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название слайда')),
                ('lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mainoffers', to='dbcore.language', verbose_name='Язык')),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='Имя компании')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Главный текст')),
                ('lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mainpages', to='dbcore.language', verbose_name='Язык')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст заголовка')),
                ('img', models.ImageField(upload_to='', verbose_name='Картинка позади текста')),
                ('main_offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='dbcore.mainoffer', verbose_name='Слайд')),
            ],
        ),
        migrations.RemoveField(
            model_name='feedbackemailentry',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productmedia',
            name='product',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='FeedbackEmailEntry',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='ProductMedia',
        ),
        migrations.AddField(
            model_name='info',
            name='main_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infos', to='dbcore.maininfo', verbose_name='Слайд'),
        ),
        migrations.AddField(
            model_name='childinfo',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childinfos', to='dbcore.info', verbose_name='Слайд'),
        ),
    ]
