# Generated by Django 4.2.3 on 2023-08-10 21:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0003_childinfo_info_language_maininfo_mainoffer_mainpage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childinfo',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='info',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст'),
        ),
    ]
