# Generated by Django 4.2.4 on 2023-09-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0004_remove_emailentry_to_email_emailentry_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='img',
            field=models.ImageField(default=None, upload_to='', verbose_name='Картинка сбоку'),
            preserve_default=False,
        ),
    ]
