# Generated by Django 4.2.3 on 2023-08-10 21:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0004_alter_childinfo_text_alter_info_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=20, verbose_name='Телефон')),
                ('text', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='childinfo',
            options={'verbose_name': 'Пример', 'verbose_name_plural': 'Примеры'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Язык', 'verbose_name_plural': 'Языки'},
        ),
        migrations.AlterModelOptions(
            name='maininfo',
            options={'verbose_name': 'Информация', 'verbose_name_plural': 'Информации'},
        ),
        migrations.AlterModelOptions(
            name='mainoffer',
            options={'verbose_name': 'Слайд с предложениями', 'verbose_name_plural': 'Слайды с предложениями'},
        ),
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name': 'Главная страница', 'verbose_name_plural': 'Главные страницы'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Предложение', 'verbose_name_plural': 'Предложения'},
        ),
    ]
