# Generated by Django 4.2.3 on 2023-08-14 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0005_feedback_alter_childinfo_options_alter_info_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Клиентская заявка', 'verbose_name_plural': 'Клиентские заявки'},
        ),
    ]
