# Generated by Django 4.2.4 on 2023-09-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0006_alter_info_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childoffer',
            name='text',
            field=models.TextField(verbose_name='Текст заголовка'),
        ),
        migrations.AlterField(
            model_name='emailentry',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлено'),
        ),
        migrations.AlterField(
            model_name='emailentry',
            name='text',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(verbose_name='Сообщение'),
        ),
    ]
