# Generated by Django 4.0.2 on 2023-09-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0007_alter_maininfo_options_remove_maininfo_lang_fullinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('ru', 'ru'), ('eng', 'eng'), ('kz', 'kz')], max_length=3, unique=True, verbose_name='Языковая раскладка'),
        ),
    ]
