# Generated by Django 4.2.4 on 2023-09-03 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0008_alter_language_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='text',
        ),
    ]
