# Generated by Django 4.2.4 on 2023-09-03 21:28

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0009_remove_info_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderChildInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('img', models.ImageField(upload_to='', verbose_name='Фото')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Пример',
                'verbose_name_plural': 'Примеры',
            },
        ),
        migrations.CreateModel(
            name='SliderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='SliderMainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliderfullinfos', to='dbcore.language', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.DeleteModel(
            name='ChildInfo',
        ),
        migrations.AddField(
            model_name='sliderinfo',
            name='main_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliderinfos', to='dbcore.slidermaininfo', verbose_name='Слайд'),
        ),
        migrations.AddField(
            model_name='sliderchildinfo',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliderchildinfos', to='dbcore.sliderinfo', verbose_name='Слайд'),
        ),
    ]
