# Generated by Django 4.2.4 on 2023-09-03 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0010_sliderchildinfo_sliderinfo_slidermaininfo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderchildinfo',
            options={'verbose_name': 'Пример (слайлдер)', 'verbose_name_plural': 'Примеры (слайлдер)'},
        ),
        migrations.AlterModelOptions(
            name='sliderinfo',
            options={'verbose_name': 'Подкатегория (слайлдер)', 'verbose_name_plural': 'Подкатегория (слайлдер)'},
        ),
        migrations.AlterModelOptions(
            name='slidermaininfo',
            options={'verbose_name': 'Категория (слайдер)', 'verbose_name_plural': 'Категории (слайдер)'},
        ),
        migrations.RenameField(
            model_name='sliderchildinfo',
            old_name='info',
            new_name='slider_info',
        ),
        migrations.RenameField(
            model_name='sliderinfo',
            old_name='main_info',
            new_name='slider_main_info',
        ),
    ]
