# Generated by Django 4.2.4 on 2023-09-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0012_alter_sliderchildinfo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderchildinfo',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
