# Generated by Django 4.2.4 on 2023-09-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0013_alter_sliderchildinfo_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.CharField(max_length=255)),
                ('to_email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name': 'Главная страница', 'verbose_name_plural': 'Главная страница'},
        ),
    ]
