# Generated by Django 4.2.4 on 2023-09-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0014_emailentry_alter_mainpage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailentry',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
