# Generated by Django 4.2.3 on 2023-09-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0015_emailentry_is_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailentry',
            options={'verbose_name': 'Имейлы', 'verbose_name_plural': 'Имейлы'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегория'},
        ),
        migrations.RemoveField(
            model_name='emailentry',
            name='from_email',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=20, verbose_name='Почта'),
        ),
    ]
