name: Restart CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4

    steps:
    - name: Restarting server
      run: |
        echo {{secrets.NOTROOT_PASS}} | sudo -S /home/notroot/promshop/script.sh
