name: Restart CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps: 
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.NOTROOT_HOST }}
        username: ${{ secrets.NOTROOT_USERNAME }}
        password: ${{ secrets.NOTROOT_PASS }}
        script: sh /home/notroot/promshop/script.sh
